### ISSUE TITLE
关于对比算法lightgcn

### ISSUE THREAD

**Issue by akajinchen** [HasiNed/giffcf#1]
您好，感谢您出色的工作和开源的代码。对比算法lightgcn的实验参数可以公布下吗，因为我用lightgcn在数据集ml-1m上实验，发现效果和论文中的差距很大

**Comment by VinciZhu** [comment]
1. LightGCN中Recall的定义与我们的有所不同，我们遵循Mult-VAE论文中的定义。
2. 所有模型的嵌入大小统一设为200。
